se nocp

" Vim Options (assumes vim-sensible)
colo molokai_transparent
se cf hi=10000 sc " Prompt
se spl=en_us,en " Spellchecking
se enc=utf-8 nostmp " Internal
se et sts=4 sw=4 " Tabs
"se fdm=syntax fdls=99 " Folding
se fo=croqj si " Formatting
se go=emgrL " Gui
se hls ic scs " Search
se lcs=tab:↹·,trail:␢,extends:⇉,precedes:⇇,nbsp:␣ sbr=↳\  " Display
se lz tf " Drawing
se mouse=a ttymouse=xterm2 " Mouse
se nobomb " Encoding
se nosol " Movement
se udf " Undo

" os-specific
if has("unix")
    se dict+=/usr/share/dict/words
    se udir=~/.vim/undo vif=~/.vim/info
elseif has("win32")
    se gfn=Cascadia_Code:h9:qCLEARTYPE
    se udir=~/vimfiles/undo vif=~/vimfiles/info
endif

" Filetype Options
au FileType gitcommit,mail,tex,text,markdown setlocal spell complete+=kspell
au FileType make setlocal noet sw=8 sts=0
au FileType tex,text,markdown setlocal tw=80 noai nocin nosi inde=

" TODO Make vimdiff legible

" Rust Language Server
let g:rustfmt_autosave = 1

" GPG Options
let g:GPGPreferSymmetric = 1

" Custom Digraphs
dig -b 8226 " U+2022 • BULLET
dig -^ 8227 " U+2023 ‣ TRIANGULAR BULLET
dig ?! 8253 " U+204d ‽ INTERROBANG
dig *: 8258 " U+2042 ⁂ ASTERISM
dig h- 8463 " U+210F ℏ PLANCK CONSTANT OVER TWO PI
dig @> 8636 " U+21BB ↻ CLOCKWISE OPEN CIRCLE ARROW
